spring:
  application:
    name: summer-practice
  cloud:
    gcp:
      project-id: ${FIREBASE_PROJECT_ID}
      credentials:
        location: ${GOOGLE_CREDENTIALS_LOCATION:classpath:unitap-firebase-key.json}
jwt:
  secret: ${JWT_SECRET}
  access-token:
    ttl: ${JWT_ACCESS_TTL}
  refresh-token:
    ttl: ${JWT_REFRESH_TTL}
